// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: proto/report.proto

package telemetrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_OK      Status = 0
	Status_STATUS_WARNING Status = 1
	Status_STATUS_UNKNOWN Status = 2
	Status_STATUS_ERROR   Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_OK",
		1: "STATUS_WARNING",
		2: "STATUS_UNKNOWN",
		3: "STATUS_ERROR",
	}
	Status_value = map[string]int32{
		"STATUS_OK":      0,
		"STATUS_WARNING": 1,
		"STATUS_UNKNOWN": 2,
		"STATUS_ERROR":   3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_report_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_report_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_report_proto_rawDescGZIP(), []int{0}
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint32                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"` // spakowane: major | minor | patch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_proto_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_proto_report_proto_rawDescGZIP(), []int{0}
}

func (x *Version) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Temp          float64                `protobuf:"fixed64,2,opt,name=temp,proto3" json:"temp,omitempty"` // też
	Humi          *float64               `protobuf:"fixed64,3,opt,name=humi,proto3,oneof" json:"humi,omitempty"`
	Enable        bool                   `protobuf:"varint,4,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_proto_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_proto_report_proto_rawDescGZIP(), []int{1}
}

func (x *DataPoint) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *DataPoint) GetTemp() float64 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *DataPoint) GetHumi() float64 {
	if x != nil && x.Humi != nil {
		return *x.Humi
	}
	return 0
}

func (x *DataPoint) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type SensorReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ver           *Version               `protobuf:"bytes,2,opt,name=ver,proto3" json:"ver,omitempty"`
	Data          []*DataPoint           `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=telemetry.Status" json:"status,omitempty"`
	Logs          string                 `protobuf:"bytes,5,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorReport) Reset() {
	*x = SensorReport{}
	mi := &file_proto_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReport) ProtoMessage() {}

func (x *SensorReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReport.ProtoReflect.Descriptor instead.
func (*SensorReport) Descriptor() ([]byte, []int) {
	return file_proto_report_proto_rawDescGZIP(), []int{2}
}

func (x *SensorReport) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SensorReport) GetVer() *Version {
	if x != nil {
		return x.Ver
	}
	return nil
}

func (x *SensorReport) GetData() []*DataPoint {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SensorReport) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_OK
}

func (x *SensorReport) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

var File_proto_report_proto protoreflect.FileDescriptor

const file_proto_report_proto_rawDesc = "" +
	"\n" +
	"\x12proto/report.proto\x12\ttelemetry\"\x1f\n" +
	"\aVersion\x12\x14\n" +
	"\x05value\x18\x01 \x01(\rR\x05value\"m\n" +
	"\tDataPoint\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x12\n" +
	"\x04temp\x18\x02 \x01(\x01R\x04temp\x12\x17\n" +
	"\x04humi\x18\x03 \x01(\x01H\x00R\x04humi\x88\x01\x01\x12\x16\n" +
	"\x06enable\x18\x04 \x01(\bR\x06enableB\a\n" +
	"\x05_humi\"\xad\x01\n" +
	"\fSensorReport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12$\n" +
	"\x03ver\x18\x02 \x01(\v2\x12.telemetry.VersionR\x03ver\x12(\n" +
	"\x04data\x18\x03 \x03(\v2\x14.telemetry.DataPointR\x04data\x12)\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.telemetry.StatusR\x06status\x12\x12\n" +
	"\x04logs\x18\x05 \x01(\tR\x04logs*Q\n" +
	"\x06Status\x12\r\n" +
	"\tSTATUS_OK\x10\x00\x12\x12\n" +
	"\x0eSTATUS_WARNING\x10\x01\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x02\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x03B%Z#example.com/myapp/proto;telemetrypbb\x06proto3"

var (
	file_proto_report_proto_rawDescOnce sync.Once
	file_proto_report_proto_rawDescData []byte
)

func file_proto_report_proto_rawDescGZIP() []byte {
	file_proto_report_proto_rawDescOnce.Do(func() {
		file_proto_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_report_proto_rawDesc), len(file_proto_report_proto_rawDesc)))
	})
	return file_proto_report_proto_rawDescData
}

var file_proto_report_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_report_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_report_proto_goTypes = []any{
	(Status)(0),          // 0: telemetry.Status
	(*Version)(nil),      // 1: telemetry.Version
	(*DataPoint)(nil),    // 2: telemetry.DataPoint
	(*SensorReport)(nil), // 3: telemetry.SensorReport
}
var file_proto_report_proto_depIdxs = []int32{
	1, // 0: telemetry.SensorReport.ver:type_name -> telemetry.Version
	2, // 1: telemetry.SensorReport.data:type_name -> telemetry.DataPoint
	0, // 2: telemetry.SensorReport.status:type_name -> telemetry.Status
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_report_proto_init() }
func file_proto_report_proto_init() {
	if File_proto_report_proto != nil {
		return
	}
	file_proto_report_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_report_proto_rawDesc), len(file_proto_report_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_report_proto_goTypes,
		DependencyIndexes: file_proto_report_proto_depIdxs,
		EnumInfos:         file_proto_report_proto_enumTypes,
		MessageInfos:      file_proto_report_proto_msgTypes,
	}.Build()
	File_proto_report_proto = out.File
	file_proto_report_proto_goTypes = nil
	file_proto_report_proto_depIdxs = nil
}
